### ISSUE TITLE
"Received an action call without an action" - Custom Action, POST Request

### ISSUE THREAD

**Issue by aejaex** [RasaHQ/rasa-sdk#111]
Rasa version: 1.4.3

Python version: 3.7

Operating system (windows, osx, ...): Mac OS X High Sierra

Issue: Custom Action via POST Request not working

Error (including full traceback): I have set up a custom action and defined it in my domain.yml, and also set up the endpoint in endpoint.yml at "http://localhost:5055/webhook", however, when I call the post request I get a 200 response but there is no output by the bot and I get a warning that "Received an action call without an action". If I call the action just by conversing with the bot it works well, the message is dispatched.

2019-11-05 19:14:14 WARNING  rasa_sdk.endpoint  - You are using an old version of rasa which might not be compatible with this version of rasa_sdk (1.4.0).
To ensure compatibility use the same version for both, modulo the last number, i.e. using version A.B.x the numbers A and B should be identical for both rasa and rasa_sdk.
2019-11-05 19:14:14 WARNING  rasa_sdk.executor  - Received an action call without an action.
127.0.0.1 - - [2019-11-05 19:14:14] "POST /webhook HTTP/1.1" 200 144 0.005133

Content of configuration file (config.yml) (if relevant):

```
language: en
pipeline: supervised_embeddings
policies:
- name: MemoizationPolicy
- name: KerasPolicy
- name: MappingPolicy
Content of domain file (domain.yml) (if relevant):
```
```
intents:
- greet
- goodbye
- affirm
- deny
- mood_great
- mood_unhappy
- bot_challenge
- bored
- joke


templates:
  utter_greet:
  - text: Hey! How are you?
  utter_cheer_up:
  - text: 'Here is something to cheer you up:'
    image: https://i.imgur.com/nGF1K8f.jpg
  utter_did_that_help:
  - text: Did that help you?
  utter_happy:
  - text: Great, carry on!
  utter_goodbye:
  - text: Bye
  utter_iamabot:
  - text: I am a bot, powered by Rasa.
  utter_joke:
  - text: Would you like to hear a joke?
  utter_onejoke:
  - text: There was once a person talking to a bot.
  utter_nojoke:
  - text: Alright, suit yourself.
  
  
actions:
- utter_greet
- utter_cheer_up
- utter_did_that_help
- utter_happy
- utter_goodbye
- utter_iamabot
- utter_joke
- utter_onejoke
- utter_nojoke
- action_main

```

```
ACTION.PY

from rasa_sdk import Action
from rasa_sdk.events import SlotSet
from datetime import datetime
from crontab import CronTab
import schedule
import timE

class ActionMain(Action):

def name(self):
    return "action_main"


def run(self, dispatcher, tracker, domain):
    
    dispatcher.utter_message("Our chatbot is live")

    return []


```

```
POST REQUEST:

import requests
import json

url = 'http://localhost:5055/webhook'

#url = "http://localhost:5055/conversations/default/execute"

headers = {'Content-type': 'application/json'}

dx = json.dumps({"name": "action_main"})

requests.post(url, data=dx, headers=headers)

```

Please help me, I am not being able to call my custom action when running via post. Thanks.
