### ISSUE TITLE
__pycache__ is created as a root user, dockerfile should not run as priviledged user

### ISSUE THREAD

**Issue by ortsaCniveK** [RasaHQ/rasa-sdk#114]
**Rasa version**: 1.4.5 (not relevant for this issue)

**Rasa SDK version**: 1.4.0

**Python version**: 3.6

**Operating system** (windows, osx, ...): Docker

**Issue**:
When running the rasa-sdk container and loading the actions module via `entrypoint.sh`, `actions/__pycache__` is created as a root user.  Since this is typically a directory, attempts to delete `__pycache__` as a non-root user will fail with error below.  

Rasa's containers (in general) should not run as root.

**Error (including full traceback)**:
```
rm: cannot remove 'actions/__pycache__/mappedActions.cpython-36.pyc': Permission denied
rm: cannot remove 'actions/__pycache__/slotChecks.cpython-36.pyc': Permission denied
rm: cannot remove 'actions/__pycache__/fillSlots.cpython-36.pyc': Permission denied
```
> Note: obviously, running `sudo rm -rf actions/__pycache` is able to clear this folder out.

**Command or request that led to error**:
```
docker-compose run action-server

rm -rf actions/__pycache__
```

**docker-compose.yml contents (abriged):**
```yml
version: 3.0
services:
  # ...
  action-server:
    image: rasa/rasa-sdk:1.4.0
    networks: ['rasa-network']
    ports:
      - '5055:5055'
    volumes:
      - ./actions:/app/actions
    command:
      - start
      - --actions
      - actions
```
