### ISSUE TITLE
Exception: not all packages are installed . To use this pipeline, please install packages that has tensorflow_text

### ISSUE THREAD

**Issue by SahithiParsi** [RasaHQ/rasa-sdk#206]
**Rasa version**:1.10.0

**Rasa SDK version**:1.10.0

**Python version**: 3.6.6 

**Operating system** (windows, osx, ...):Windows 10: 

**Issue**:Exception: not all packages are installed . To use this pipeline, please install packages that has tensorflow_text

**Error (including full traceback)**:
```
![rasa_tensrflow_exception](https://user-images.githubusercontent.com/16195067/80693871-4bb31380-8af1-11ea-9acd-efb67f036771.PNG)


```

**Command or request that led to error**:
```
rasa train
```

**Content of configuration file (config.yml)** (if relevant):
```yml
# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: en
pipeline:
  - name: ConveRTTokenizer
  - name: ConveRTFeaturizer
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: "char_wb"
    min_ngram: 1
    max_ngram: 4
  - name: DIETClassifier
    epochs: 100
  - name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 100

# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
  - name: MemoizationPolicy
  - name: TEDPolicy
    max_history: 5
    epochs: 100
  - name: MappingPolicy

```

**Content of domain file (domain.yml)** (if relevant):
```yml

intents:
  - greet
  - goodbye
  - affirm
  - deny
  - mood_great
  - mood_unhappy
  - bot_challenge
  - news

entities:
  - sector
  - countries
  - technology_theme
  
slots:
   countries:
      type: text
   sector:
      type: text
   technology_theme:
      type: text
      
responses:
  utter_greet:
  - text: "Hey! How are you?"
  utter_news:
   - text: "Here is the news:"
  utter_cheer_up:
  - text: "Here is something to cheer you up:"
    image: "https://i.imgur.com/nGF1K8f.jpg"
  utter_did_that_help:
  - text: "Did that help you?"

  utter_happy:
  - text: "Great, carry on!"

  utter_goodbye:
  - text: "Bye"

  utter_iamabot:
  - text: "I am a bot, powered by Rasa."

actions:
  - utter_news
  
session_config:
  session_expiration_time: 60
  carry_over_slots_to_new_session: true

```

**Contents of actions.py** (if  relevant):
```python
# This files contains your custom actions which can be used to run
# custom Python code.
#
# See this guide on how to implement these action:
# https://rasa.com/docs/rasa/core/actions/#custom-actions/


# This is a simple example for a custom action which utters "Hello World!"

# from typing import Any, Text, Dict, List
#
from rasa_sdk import Action, Tracker
from rasa_sdk.executor import CollectingDispatcher
#
#
# class ActionHelloWorld(Action):

    # def name(self) -> Text:
        # return "action_hello_world"

    # def run(self, dispatcher: CollectingDispatcher,
            # tracker: Tracker,
            # domain: Dict[Text, Any]) -> List[Dict[Text, Any]]:

        # dispatcher.utter_message(text="Hello World!")

        # return []

class utter_news(Action):

    def name(self) -> Text:
        return "action_hello_world"

    def run(self, dispatcher: CollectingDispatcher,
            tracker: Tracker,
            domain: Dict[Text, Any]) -> List[Dict[Text, Any]]:

            if tracker.get_slot('counties') == 'india':
        dispatcher.utter_message(text="https://disruptor.globaldata.com/News/Dashboard?location=100110")
            elif tracker.get_slot('counties') == 'china':
        dispatcher.utter_message(text="https://disruptor.globaldata.com/News/NewsListing?location=100053")
            else:
        dispatcher.utter_message(text="https://disruptor.globaldata.com/News/Dashboard/")
        return []

```
