### ISSUE TITLE
Next slot asked not consistent when returning to a form in unhappy path

### ISSUE THREAD

**Issue by nbeuchat** [RasaHQ/rasa-sdk#389]
**Rasa version**: 2.2.1

**Rasa SDK version**: 2.2.0

**Python version**: 3.7.9 

**Operating system** (windows, osx, ...): Ubuntu

**Issue**:
I have a form with a `FormValidationAction` which overrides the `required_slots` method. I have a rule for an unhappy path when user ask why we need this info. The bot answers the question and then comes back to the form directly (see rules below). 

The problem is that although the slot has not been filled, the next question asked is not the same (ie: not the first unfilled slot in the list of slots returned by `required_slots`). It even seems that it is *not* using the list from the `required_slots` but the one from the domain. 

This gives rise to weird conversations like the one below:

![image](https://user-images.githubusercontent.com/8236283/103645442-477ca700-4f58-11eb-871a-6a7fe1b849a8.png)

In this example, I would expect the bot to ask for the `user_contact` again. Also, `has_pet` being set to `False`, the `has_pet_type` question should not even be asked at all (see the `required_slots` function below). 

**Content of domain file (domain.yml)**:
```yml
forms:
  form_preferences:
    ...
    has_pet:
    - intent: deny
      type: from_intent
      value: false
    - entity: animal
      type: from_entity
    - intent: affirm
      type: from_intent
      value: true
    has_pet_type:
    - entity: animal
      type: from_entity
    user_contact:
    - entity: phone_number
      type: from_entity
    - entity: email
      type: from_entity
```

**Contents of actions.py**:
```python
class ValidatePreferencesForm(FormValidationAction):
    def name(self) -> Text:
        return "validate_form_preferences"

    async def required_slots(
        self,
        slots_mapped_in_domain: List[Text],
        dispatcher: CollectingDispatcher,
        tracker: Tracker,
        domain: DomainDict,
    ) -> Optional[List[Text]]:
        # TODO: do not override slots_mapped_in_domain once Rasa X overriding issue is addressed
        # See: https://github.com/RasaHQ/rasa/issues/7460

        slots_mapped_in_domain = [
            ...
            "has_pet",
            "has_pet_type",
            "user_contact",
        ]

        if tracker.get_slot("has_pet") is not True:
            pop_from_list(slots_mapped_in_domain, "has_pet_type")

        return slots_mapped_in_domain
```

**Rules**
```
- rule: Activate preferences form
  steps:
  - action: action_introduce_form_preferences
  - action: form_preferences
  - active_loop: form_preferences
 
- rule: Explain within form preferences
  condition:
  - active_loop: form_preferences
  steps:
  - intent: explain
  - action: action_explain
  - action: form_preferences
```
