### ISSUE TITLE
Add Support for headers/basic auth

### ISSUE THREAD

**Issue by wochinge** [RasaHQ/rasa-sdk#56]
Based on https://github.com/RasaHQ/rasa_core/issues/1796

**Comment by khilnani** [comment]
Will take a look. Need double check I can setup the dev branch/master. Thanks @wochinge

**Comment by tmbo** [comment]
I don't think the SDK should do that directly, there is no benefit over using existing solutions (e.g. use docker compose and spin up an Nginx with basic auth before the action server).

**Comment by khilnani** [comment]
That's reasonable. If the action is fronted by nginx, does the endpoints config support sending headers/auth credentials or would some changes be needed to support specifying and sending headers?

**Comment by tmbo** [comment]
There should be support for basic auth, if you put something like this in the endpoint config:
```
actions:
  url: http://localhost:5055
  basic_auth:
    username: myuser
    password: mypassword
```

**Comment by khilnani** [comment]
Thanks, that addresses the core need!


Thanks,
Nik

________________________________

**Comment by tmbo** [comment]
You are welcome 😃 

Just for future reference: If you want to use e.g. token based auth, you can also directly set headers
```
actions:
  url: http://localhost:5055
  headers:
    Authentication: "bearer ..."
```
